language: r
r:
<<<<<<< HEAD
  - 3.4
=======
  - 3.2
>>>>>>> multi
##  - release
  - devel

sudo: false

cache: apt

os:
  - linux

r_check_args: --as-cran

r_packages:
  - TMB

before_install:
  - cd ./stockassessment
